/*
 * @Author : SWAPNAIT
 * @CreatedDate : 25/07/2023
 * @Description : To Capture Employee Details
 * @LastModifiedBy : Date			Person Name			Description
 * 					 27-07-2023		XYZ					Adding the Joining Date Varaible 			
 */
public class EmployeeDetails {
    Public string studName;
    Public string CourseDetails;
    Public string StdId;
    Private string courseId;
    Public string BatchNumber;
	public Date joingDate;
}