public class Mathoperation {
    public static void addMethod(integer x, integer y, integer z){
        system.debug('Addition Result :' +(x+y+z));
    }
     public static void mulMethod(integer x, integer y){
        system.debug('Multily Result :' +(x*y));
    }

     public static void DivMethod(integer x, integer y){
        system.debug('Div Result :' +(x/y));
    }

     public static void subMethod(integer x, integer y){
         system.debug('Sub Result :' +(x-y));
        
    }
    public static Integer Multiply(integer x, integer y, integer z){
        return (x*y*z);
    }


}