/*
 * @description : This class used for Lead DMLOperations
 *  @Author : SWAPNAIT
 * @Ceated Date : 31-07-2023
 * @Last Modified Date			Person			Comments
 */
public class MathHelper {
	
    /*
     * @description : This Method is used for Addition
     * @Author :
     */
    Public static void Addition(integer x, integer y){
        system.debug('Sum of Values :'+(x+y));
        
    }
    
    /*
     * @description : This Method is used for Multiplication
     * @Author :
     */
    Public static void Multi(integer x, integer y, integer z){
        system.debug('Multiplication of Values :'+(x*y*z));
        
    }
    /*
     * @description : This Method is used for Concatenation
     * @Author :
     */
    public void Concatenate(string s1, string s2){
        system.debug('combining two values :'+s1+s2);
    }
         
}